[package]
name = "otp"
version = "0.1.0"
authors = ["tom badger"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.3"
phf = { version = "0.8", features = ["macros"] }
