name: Generate and publish release binaries

on:
  release:
    types: [published]

jobs:
  linux-x86_64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          default: true

      - name: Build binary
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target x86_64-unknown-linux-musl
          use-cross: true

      - name: Optimize and package binary
        run: |
          cd target/x86_64-unknown-linux-musl/release
          strip otp
          chmod +x otp
          tar -c otp | gzip > otp-${{ github.event.release.tag-name }}-linux-x86_64.tar.gz
      - name: Upload binary
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: otp-${{ github.event.release.tag-name }}-linux-x86_64.tar.gz

  macos-x86_64:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          default: true

      - name: Build binary
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
          use-cross: true

      - name: Optimize and package binary
        run: |
          cd target/release
          strip otp
          chmod +x otp
          mkdir dmg
          mv otp dmg/
          hdiutil create -fs HFS+ -srcfolder dmg -volname otp otp-${{ github.event.release.tag-name }}-macos-x86_64.dmg
      - name: Upload binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: otp-${{ github.event.release.tag-name }}-macos-x86_64.dmg